np/news/__init__.py
from .routes import news_b

np/news/routes.py
from flask import Blueprint, render_template, url_for, redirect
from np import News, Events, ProjectsReport


news_b = Blueprint("news_", __name__)


def trim(text):
    d = []
    for i in range(1, 201):
        d.append(text[i])

    return "".join(d)


def inc(i):
    return i+1


def dec(i):
    return i-1

@news_b.route("/newses", methods=['GET', 'POST'])
def news():
    data = News.query.limit(8).all()
    data2 = Events.query.limit(3).all()
    data3 = ProjectsReport.query.all()
    return render_template("news/news.html", title="News and Events", data=data,
                           data2=data2, data3=data3, trim=trim)


@news_b.route("/newses/page/<int:nid>", methods=['GET', 'POST'])
def news_page(nid):
    data = News.query.get(nid)
    last_id = News.query.order_by(News.id.desc()).first().id
    return render_template("news/page.html", title="News and Events",
                           data=data, inc=inc, dec=dec, last_id=last_id)


@news_b.route("/newses/all", methods=['GET', 'POST'])
def all_news():
    data = News.query.all()
    return render_template("news/all-news.html", title="News and Events", data=data, trim=trim)


@news_b.route("/events/page/<int:nid>", methods=['GET', 'POST'])
def events_page(nid):
    data = Events.query.get(nid)
    last_id = Events.query.order_by(Events.id.desc()).first().id
    return render_template("news/events.html", title="News and Events",
                           data=data, inc=inc, dec=dec, last_id=last_id)

@news_b.route("/events/all", methods=['GET', 'POST'])
def all_events():
    data = Events.query.all()
    return render_template("news/all-events.html", title="News and Events", data=data, trim=trim)


@news_b.route("/report/page/<int:nid>", methods=['GET', 'POST'])
def reports_page(nid):
    data = ProjectsReport.query.get(nid)
    last_id = ProjectsReport.query.order_by(ProjectsReport.id.desc()).first().id
    return render_template("news/reports.html", title="News and Events",
                           data=data, inc=inc, dec=dec, last_id=last_id)


@news_b.route("/reports/all", methods=['GET', 'POST'])
def all_reports():
    data = ProjectsReport.query.all()
    return render_template("news/all-reports.html", title="News and Events", data=data, trim=trim)

np/templates/news/all-events.html
{% extends "template.html" %}
{% block contents %}
    <div class="container-md container-lg my-5">
        <div class="bg-white f-msg2 p-5 text-secondary">
            <h1 class="text-primary font-weight-bold">Events</h1>
                <div class="row">
                    {% for i in data %}
                        <div class="w-100 p-3 my-3 shadow">
                            <h6><i class="fa fa-clock"></i> {{ i.date }} <i class="fa fa-th"></i> Events</h6>
                            <h4>{{ i.title }}</h4>
                            <h6>{{ i.author }}</h6>
                            <a class="btn btn-primary mt-3" href="{{ url_for('news_.events_page', nid=i.id) }}">Read More</a>
                        </div>
                    {% endfor %}
                </div>
        </div>
    </div>
{% endblock contents %}

np/templates/news/all-news.html
{% extends "template.html" %}
{% block contents %}
    <div class="container-md container-lg my-5">
        <div class="bg-white f-msg2 p-5 text-secondary">
            <h1 class="text-primary font-weight-bold">News</h1>
                <div class="row">
                    {% for i in data %}
                        <div class="p-2 col-lg-3 col-md-3 col-sm-6 col-5">
                            <div class="p-3 shadow h-100">
                                <h6><i class="fa fa-clock"></i> {{ i.date }} <i class="fa fa-th"></i> News</h6>
                                <h4>{{ i.title }}</h4>
                                <p>{{ trim(i.text) }}</p>
                                <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+i.img1) }}">

                                {% if i.img2 != None %}
                                    <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+i.img2) }}">
                                {% endif %}

                                {% if i.img3 != None %}
                                    <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+i.img3) }}">
                                {% endif %}

                                {% if i.img4 != None %}
                                    <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+i.img4) }}">
                                {% endif %}

                                {% if i.img5 != None %}
                                    <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+i.img5) }}">
                                {% endif %}

                                <a class="btn btn-primary mt-3" href="{{ url_for('news_.news_page', nid=i.id) }}">Read More</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
        </div>
    </div>
{% endblock contents %}

np/templates/news/all-reports.html
{% extends "template.html" %}
{% block contents %}
    <div class="container-md container-lg my-5">
        <div class="bg-white f-msg2 p-5 text-secondary">
            <h1 class="text-primary font-weight-bold">Projects Progress Report</h1>
            <div>
                {% for i in data %}
                    <div class="w-100 p-3 my-3 shadow">
                        <h6><i class="fa fa-clock"></i> {{ i.date }} <i class="fa fa-th"></i> Projects Progress Report</h6>
                        <h4>{{ i.title }}</h4>
                        <img class="w-25 rounded my-2" src="{{ url_for('static', filename='events/'+i.img1) }}">
                        <br><br>
                        <a class="btn btn-primary mt-3" href="{{ url_for('news_.reports_page', nid=i.id) }}">Read More</a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock contents %}

np/templates/news/events.html
{% extends "template.html" %}
{% block contents %}
    <div class="container-md container-lg my-5">
        <div class="bg-white f-msg2 p-5 text-secondary">

            <div class="bg-primary py-4 my-4 text-white text-center" style="width: 100px; height: 100px;">
                <h5>{{ data.date }}</h5>
            </div>
            <i class="fa fa-file-text mb-3"> Events</i>
            <h4 class="text-muted font-weight-bold">{{ data.title }}</h4>
            <h6>{{ data.author }}</h6>
            <p>{{ data.text }}</p>

            <div class="d-flex">
                {% if data.id != 1 %}
                    <a class="btn btn-primary mt-3 float-start me-auto" href="{{ url_for('news_.events_page', nid=dec(data.id)) }}">Previous</a>
                {% endif %}

                {% if data.id != last_id %}
                    <a class="btn btn-primary mt-3 float-end ms-auto" href="{{ url_for('news_.events_page', nid=inc(data.id)) }}">Next</a>
                {% endif %}
            </div>


        </div>
    </div>
{% endblock contents %}

np/templates/news/news.html
{% extends "template.html" %}
{% block contents %}
    <div class="container-md container-lg my-5">
        <div class="bg-white f-msg2 p-5 text-secondary">
            <h1 class="text-primary font-weight-bold">News</h1>
                <div class="row">
                    {% for i in data %}
                        <div class="p-2 col-lg-3 col-md-3 col-sm-6 col-5">
                            <div class="p-3 shadow h-100">
                                <h6><i class="fa fa-clock"></i> {{ i.date }} <i class="fa fa-th"></i> News</h6>
                                <h4>{{ i.title }}</h4>
                                <p>{{ trim(i.text) }}</p>
                                <a class="btn btn-primary mt-3" href="{{ url_for('news_.news_page', nid=i.id) }}">Read More</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <a class="btn btn-outline-primary w-100 my-3" href="{{ url_for('news_.all_news') }}">See All News</a>

                <h1 class="text-primary font-weight-bold my-3">Events</h1>
                <div>
                    {% for i in data2 %}
                        <div class="w-100 p-3 my-3 shadow">
                            <h6><i class="fa fa-clock"></i> {{ i.date }} <i class="fa fa-th"></i> Events</h6>
                            <h4>{{ i.title }}</h4>
                            <h6>{{ i.author }}</h6>
                            <a class="btn btn-primary mt-3" href="{{ url_for('news_.events_page', nid=i.id) }}">Read More</a>
                        </div>
                    {% endfor %}
                </div>
                <a class="btn btn-outline-primary w-100 my-3" href="{{ url_for('news_.all_events') }}">See All Events</a>

                <h1 class="text-primary font-weight-bold my-3">Projects Progress Report</h1>
                <div>
                    {% for i in data3 %}
                        <div class="w-100 p-3 my-3 shadow">
                            <h6><i class="fa fa-clock"></i> {{ i.date }} <i class="fa fa-th"></i> Projects Progress Report</h6>
                            <h4>{{ i.title }}</h4>
                            <img class="w-25 rounded my-2" src="{{ url_for('static', filename='events/'+i.img1) }}">
                            <br><br>
                            <a class="btn btn-primary mt-3" href="{{ url_for('news_.reports_page', nid=i.id) }}">Read More</a>
                        </div>
                    {% endfor %}
                </div>
                <a class="btn btn-outline-primary w-100 my-3" href="{{ url_for('news_.all_reports') }}">See All Projects Progress Report</a>
        </div>
    </div>
{% endblock contents %}

np/templates/news/page.html
{% extends "template.html" %}
{% block contents %}
    <div class="container-md container-lg my-5">
        <div class="bg-white f-msg2 p-5 text-secondary">

            <div class="bg-primary py-4 my-4 text-white text-center" style="width: 100px; height: 100px;">
                <h5>{{ data.date }}</h5>
            </div>
            <i class="fa fa-file-text mb-3"> News</i>
            <h4 class="text-muted font-weight-bold">{{ data.title }}</h4>
            <p>{{ data.text }}</p>

            <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+data.img1) }}">

            {% if data.img2 != None %}
                <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+data.img2) }}">
            {% endif %}

            {% if data.img3 != None %}
                <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+data.img3) }}">
            {% endif %}

            {% if data.img4 != None %}
                <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+data.img4) }}">
            {% endif %}

            {% if data.img5 != None %}
                <img class="w-100 rounded my-2" src="{{ url_for('static', filename='news/'+data.img5) }}">
            {% endif %}

            <div class="d-flex">
                {% if data.id != 1 %}
                    <a class="btn btn-primary mt-3 float-start me-auto" href="{{ url_for('news_.news_page', nid=dec(data.id)) }}">Previous</a>
                {% endif %}

                {% if data.id != last_id %}
                    <a class="btn btn-primary mt-3 float-end ms-auto" href="{{ url_for('news_.news_page', nid=inc(data.id)) }}">Next</a>
                {% endif %}
            </div>


        </div>
    </div>
{% endblock contents %}

np/templates/news/reports.html
{% extends "template.html" %}
{% block contents %}
    <div class="container-md container-lg my-5">
        <div class="bg-white f-msg2 p-5 text-secondary">

            <div class="bg-primary py-4 my-4 text-white text-center" style="width: 100px; height: 100px;">
                <h5>{{ data.date }}</h5>
            </div>
            <i class="fa fa-file-text mb-3"> Projects Progress Report</i>
            <h4 class="text-muted font-weight-bold">{{ data.title }}</h4>
            <img class="w-25 rounded my-2" src="{{ url_for('static', filename='events/'+data.img1) }}">
            <p>{{ data.text }}</p>

            <div class="d-flex">
                {% if data.id != 1 %}
                    <a class="btn btn-primary mt-3 float-start me-auto" href="{{ url_for('news_.reports_page', nid=dec(data.id)) }}">Previous</a>
                {% endif %}

                {% if data.id != last_id %}
                    <a class="btn btn-primary mt-3 float-end ms-auto" href="{{ url_for('news_.reports_page', nid=inc(data.id)) }}">Next</a>
                {% endif %}
            </div>


        </div>
    </div>
{% endblock contents %}